CREATE TYPE "public"."property_type" AS ENUM('WEG', 'MV');--> statement-breakpoint
CREATE TYPE "public"."unit_type" AS ENUM('apartment', 'office', 'garden', 'parking');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_building" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_building_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyId" integer NOT NULL,
	"street" varchar(256) NOT NULL,
	"houseNumber" varchar(50) NOT NULL,
	"postalCode" varchar(20),
	"city" varchar(100),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_property" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_property_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"propertyNumber" varchar(50) NOT NULL,
	"name" varchar(256) NOT NULL,
	"type" "property_type" NOT NULL,
	"managerId" varchar(255),
	"accountantId" varchar(255),
	"declarationFileUrl" text,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "pg-drizzle_property_propertyNumber_unique" UNIQUE("propertyNumber")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_unit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_unit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"buildingId" integer NOT NULL,
	"unitNumber" varchar(50) NOT NULL,
	"type" "unit_type" NOT NULL,
	"floor" integer,
	"entrance" varchar(50),
	"size" numeric(10, 2),
	"co_ownership_share" numeric(10, 6),
	"constructionYear" integer,
	"rooms" numeric(4, 1),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_building" ADD CONSTRAINT "pg-drizzle_building_propertyId_pg-drizzle_property_id_fk" FOREIGN KEY ("propertyId") REFERENCES "public"."pg-drizzle_property"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_property" ADD CONSTRAINT "pg-drizzle_property_managerId_user_id_fk" FOREIGN KEY ("managerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_property" ADD CONSTRAINT "pg-drizzle_property_accountantId_user_id_fk" FOREIGN KEY ("accountantId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_property" ADD CONSTRAINT "pg-drizzle_property_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_unit" ADD CONSTRAINT "pg-drizzle_unit_buildingId_pg-drizzle_building_id_fk" FOREIGN KEY ("buildingId") REFERENCES "public"."pg-drizzle_building"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "building_property_idx" ON "pg-drizzle_building" USING btree ("propertyId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "property_number_idx" ON "pg-drizzle_property" USING btree ("propertyNumber");--> statement-breakpoint
CREATE INDEX "property_type_idx" ON "pg-drizzle_property" USING btree ("type");--> statement-breakpoint
CREATE INDEX "property_created_by_idx" ON "pg-drizzle_property" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "unit_building_idx" ON "pg-drizzle_unit" USING btree ("buildingId");--> statement-breakpoint
CREATE INDEX "unit_type_idx" ON "pg-drizzle_unit" USING btree ("type");